"""empty message

Revision ID: 10483b9d027a
Revises: 48612dec06ac
Create Date: 2026-06-11 19:11:15.719681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10483b9d027a'
down_revision = '48612dec06ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_before', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('position_after', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('position_after')
        batch_op.drop_column('position_before')

    # ### end Alembic commands ###
