"""empty message

Revision ID: 48612dec06ac
Revises: c99e825f9c38
Create Date: 2026-06-08 20:33:36.031899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48612dec06ac'
down_revision = 'c99e825f9c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
